spring:
  application:
    name: BlogAPI
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect